server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.uncle.bean
#  config-location: classpath:mybatis-config.xml